[project]
name = "pwrd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "t.j.neep@bham.ac.uk" }
]
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.3",
    "fsspec>=2026.2.0",
    "geopandas>=1.1.2",
    "httpx>=0.28.1",
    "numpy>=2.4.3",
    "pandas>=3.0.1",
    "requests>=2.32.5",
    "xvec>=0.5.2",
    "zarr>=3.1.5",
]

[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-cov>=7.1.0",
    "pytest-httpx>=0.36.0",
]
marimo = [
    "aiohttp>=3.13.3",
    "cartopy>=0.25.0",
    "pwrd",
    "geopandas>=1.1.2",
    "joblib>=1.5.3",
    "marimo>=0.20.4",
    "matplotlib>=3.10.8",
    "pandas>=3.0.1",
    "rioxarray>=0.22.0",
    "xarray[complete]>=2026.2.0",
    "xvec>=0.5.2",
]

[tool.uv]
# There seems to have been an increased number of compromised packages
# recently. By limiting packages to older than 7 days, we can
# hopefully mitigate this slightly (although no method is perfect)
exclude-newer = "7 days"

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
pwrd = { workspace = true, editable = true }

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint]
extend-select = ["TD003", "D"]
ignore = [
   "D105",  # Don't need docstrings on magic methods
]

